spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ #注册中心的地址
  datasource:  #数据库配置
    url: jdbc:mysql://localhost:3306/db_health?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource